<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ethan Pisterman">

<title>Analysis of Variance</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="anova_files/libs/clipboard/clipboard.min.js"></script>
<script src="anova_files/libs/quarto-html/quarto.js"></script>
<script src="anova_files/libs/quarto-html/popper.min.js"></script>
<script src="anova_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="anova_files/libs/quarto-html/anchor.min.js"></script>
<link href="anova_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="anova_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="anova_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="anova_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="anova_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Analysis of Variance</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
<p class="subtitle lead">In Class Activity</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Ethan Pisterman </p>
          </div>
  </div>
    
  
    
  </div>
  
<div>
  <div class="abstract">
    <div class="block-title">Abstract</div>
    <p>This analysis examines the effects of diet and gender on weight loss using ANOVA models. Diet significantly impacts weight loss, with Diet 3 producing the greatest results. Gender alone has no meaningful effect, but males on Diet 3 show significantly higher weight loss. The interaction model explains 20% of the variation, confirming diet as the strongest predictor of weight loss.</p>
  </div>
</div>


</header>


<section id="introduction" class="level3">
<h3 class="anchored" data-anchor-id="introduction">Introduction</h3>
<p>This analysis investigates the effects of diet and gender on weight loss over six weeks using data from 76 participants. The dataset includes demographic information (age, height, and gender), initial and post-diet weights, and one of three diet plans. Through exploratory data analysis and statistical modeling, we aim to determine whether diet significantly affects weight loss, whether gender plays a role, and if there is an interaction between diet and gender that impacts results. Using one-way and two-way ANOVA models, along with post-hoc tests, this study identifies key patterns and explains how much of the variability in weight loss is attributable to these factors. There are 76 observations of individuals with the following characteristics:</p>
<ul>
<li>Gender (0/1)</li>
<li>Age (earth years. 🤓)</li>
<li>Height (cm)</li>
<li>Pre.weight &amp; weight6weeks (kg)</li>
<li>Diet (1,2,3)</li>
</ul>
<p>The data are located as a CSV file named <code>DietData.csv</code> linked from the Canvas page. Load the data in and format things so they look correctly to you.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load the data here</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"~/Desktop/ENVS  543/ENVS543/dietdata.csv"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(GGally)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="exploratory-data-analysis" class="level2">
<h2 class="anchored" data-anchor-id="exploratory-data-analysis">Exploratory Data Analysis</h2>
<p>One of the first things to do is to look at the data and see if there are any obvious things. Go ahead and explore these data visually. What do you see?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Data visualization</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   76 obs. of  7 variables:
 $ Person      : int  1 2 3 4 5 6 7 8 9 10 ...
 $ gender      : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Age         : int  22 46 55 33 50 50 37 28 28 45 ...
 $ Height      : int  159 192 170 171 170 201 174 176 165 165 ...
 $ pre.weight  : int  58 60 64 64 65 66 67 69 70 70 ...
 $ Diet        : int  1 1 1 1 1 1 1 1 1 1 ...
 $ weight6weeks: num  54.2 54 63.3 61.1 62.2 64 65 60.5 68.1 66.9 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Person          gender            Age            Height     
 Min.   : 1.00   Min.   :0.0000   Min.   :16.00   Min.   :141.0  
 1st Qu.:19.75   1st Qu.:0.0000   1st Qu.:32.50   1st Qu.:163.8  
 Median :40.50   Median :0.0000   Median :39.00   Median :169.0  
 Mean   :39.87   Mean   :0.4342   Mean   :39.22   Mean   :170.8  
 3rd Qu.:59.25   3rd Qu.:1.0000   3rd Qu.:47.25   3rd Qu.:175.2  
 Max.   :78.00   Max.   :1.0000   Max.   :60.00   Max.   :201.0  
   pre.weight         Diet        weight6weeks  
 Min.   :58.00   Min.   :1.000   Min.   :53.00  
 1st Qu.:66.00   1st Qu.:1.000   1st Qu.:61.95  
 Median :72.00   Median :2.000   Median :68.95  
 Mean   :72.29   Mean   :2.039   Mean   :68.34  
 3rd Qu.:78.00   3rd Qu.:3.000   3rd Qu.:73.67  
 Max.   :88.00   Max.   :3.000   Max.   :84.50  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check for missing values</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(data))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(gender, Age, Height, pre.weight, weight6weeks, Diet) <span class="ot">-&gt;</span> pair_comp</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggpairs</span>(pair_comp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="anova_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="key-insights-from-output" class="level3">
<h3 class="anchored" data-anchor-id="key-insights-from-output">Key Insights from Output:</h3>
<ol type="1">
<li><p><strong>Age</strong>: The participants’ ages range from 16 to 60, with a median age of 39, representing a middle-aged group overall.</p></li>
<li><p><strong>Height</strong>: Heights range from 141 cm to 201 cm, with an average height of about 171 cm, showing a wide variation in stature.</p></li>
<li><p><strong>Pre.weight and Weight Change</strong>:</p>
<ul>
<li><p>Pre-experiment weights range from 58 kg to 88 kg, with a mean of 72.3 kg.</p></li>
<li><p>Post-experiment weights (6 weeks later) are slightly lower on average (mean = 68.3 kg), suggesting a potential weight loss trend.</p></li>
</ul></li>
<li><p><strong>Diet Groups</strong>: Participants are evenly distributed across the three diet types (mean ~ 2.0), allowing for fair comparisons between groups.</p></li>
<li><p><strong>Gender</strong>: Around 43% of participants are coded as <code>1</code>, suggesting a near-balanced gender distribution.</p></li>
</ol>
</section>
</section>
<section id="estimating-mean-values" class="level2">
<h2 class="anchored" data-anchor-id="estimating-mean-values">Estimating Mean Values</h2>
<p>Make a table of Weight Loss by gender and diet.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Table output</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> </span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(gender, Age, pre.weight, Diet, weight6weeks) <span class="ot">-&gt;</span> weight_loss</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>weight_loss <span class="sc">%&gt;%</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">loss =</span> pre.weight <span class="sc">-</span> weight6weeks) <span class="ot">-&gt;</span> weight_loss</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>summary_table <span class="ot">&lt;-</span> weight_loss <span class="sc">%&gt;%</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(gender, Diet) <span class="sc">%&gt;%</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean_loss =</span> <span class="fu">mean</span>(loss, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(summary_table, <span class="at">caption =</span> <span class="st">"Mean Weight Loss by Gender and Diet"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Mean Weight Loss by Gender and Diet</caption>
<thead>
<tr class="header">
<th style="text-align: right;">gender</th>
<th style="text-align: right;">Diet</th>
<th style="text-align: right;">mean_loss</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3.050000</td>
</tr>
<tr class="even">
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2.607143</td>
</tr>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">5.880000</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3.650000</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">4.109091</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">4.233333</td>
</tr>
</tbody>
</table>
</div>
</div>
<section id="key-insights" class="level3">
<h3 class="anchored" data-anchor-id="key-insights">Key Insights:</h3>
<ol type="1">
<li><p><strong>Gender Differences</strong>:</p>
<ul>
<li><p>Gender <code>0</code> (e.g., Male) and Gender <code>1</code> (e.g., Female) show varying weight loss trends across diets, with females generally losing more weight on average in most diets.</p>
<ul>
<li>Example: Diet 2 (Male: 2.61 kg vs.&nbsp;Female: 4.11 kg).</li>
</ul></li>
</ul></li>
<li><p><strong>Most Effective Diets</strong>:</p>
<ul>
<li><p><strong>Gender <code>0</code></strong>: Diet 3 has the highest mean weight loss (5.88 kg).</p></li>
<li><p><strong>Gender <code>1</code></strong>: Diet 3 also shows strong results (4.23 kg), but Diet 2 is close (4.11 kg).</p></li>
</ul></li>
<li><p><strong>Least Effective Diets</strong>:</p>
<ul>
<li><p><strong>Gender <code>0</code></strong>: Diet 2 results in the lowest mean weight loss (2.61 kg).</p></li>
<li><p><strong>Gender <code>1</code></strong>: Diet 1 has the lowest mean weight loss (3.65 kg).</p></li>
</ul></li>
</ol>
</section>
</section>
<section id="way-analysis-of-variance" class="level2">
<h2 class="anchored" data-anchor-id="way-analysis-of-variance">1-Way Analysis of Variance</h2>
<p><em>Diet Issues:</em></p>
<p>The underlying linear model.</p>
<p><span class="math display">\[
y_{ij} = \mu + \tau_{Diet, i} + \epsilon_j
\]</span></p>
<p>Test the null hypothesis, <span class="math inline">\(H_O:\)</span> <em>There is no effect of diet on weight loss</em> (e.g., <span class="math inline">\(\tau_{Diet-1} = \tau_{Diet-2} = \tau_{Diet-3} = 0.0\)</span>). Is there evidence for one diet producing more weight loss than the others? Create an <code>aov</code> analysis and assign it to the variable <code>fit.diet</code> and examine its contents.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define model</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>fit.diet <span class="ot">&lt;-</span> <span class="fu">aov</span>(loss <span class="sc">~</span> <span class="fu">factor</span>(Diet), <span class="at">data =</span> weight_loss)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>fit.diet</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
   aov(formula = loss ~ factor(Diet), data = weight_loss)

Terms:
                factor(Diet) Residuals
Sum of Squares       60.5270  410.4018
Deg. of Freedom            2        73

Residual standard error: 2.371064
Estimated effects may be unbalanced</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(fit.diet)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: loss
             Df Sum Sq Mean Sq F value   Pr(&gt;F)   
factor(Diet)  2  60.53 30.2635  5.3831 0.006596 **
Residuals    73 410.40  5.6219                    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p><strong>ANOVA Results:</strong></p>
<ol type="1">
<li><p><strong>Evidence Against the Null Hypothesis</strong>:</p>
<ul>
<li><p>The p-value for the <code>factor(Diet)</code> term is <strong>0.0066</strong>, which is smaller than the significance threshold of 0.05.</p></li>
<li><p>This provides strong evidence to reject H0H_0H0​. Hence, there is a statistically significant difference in weight loss among the diet groups.</p></li>
</ul></li>
<li><p><strong>Variance Partitioning</strong>:</p>
<ul>
<li>The Sum of Squares for <code>factor(Diet)</code> is <strong>60.53</strong>, while the residual variance is larger (<strong>410.40</strong>). This indicates that while diet contributes to differences in weight loss, individual variability or other factors explain a larger portion of the variation.</li>
</ul></li>
<li><p><strong>F-Statistic</strong>:</p>
<ul>
<li>The F-value of <strong>5.38</strong> quantifies the ratio of diet-related variance to unexplained variance. The high value further supports the significance of diet as a factor.</li>
</ul></li>
<li><p><strong>Residual Standard Error</strong>:</p>
<ul>
<li>The residual standard error of <strong>2.37</strong> indicates the average deviation of observed weight loss values from the model predictions.</li>
</ul></li>
</ol>
<p>Are they all significantly different? Try the <code>TukeyHSD()</code> Interpret the results.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Posthoc test</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>tuk <span class="ot">&lt;-</span> <span class="fu">TukeyHSD</span>(fit.diet)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>tuk</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = loss ~ factor(Diet), data = weight_loss)

$`factor(Diet)`
         diff        lwr      upr     p adj
2-1 -0.032000 -1.6530850 1.589085 0.9987711
3-1  1.848148  0.2567422 3.439554 0.0188047
3-2  1.880148  0.3056826 3.454614 0.0152020</code></pre>
</div>
</div>
<p><strong>Post-hoc Summary:</strong></p>
<ol type="1">
<li><p><strong>Comparison 2 vs.&nbsp;1</strong>:</p>
<ul>
<li><p><strong>Difference</strong>: -0.032</p></li>
<li><p><strong>Confidence Interval</strong>: [-1.653, 1.589]</p></li>
<li><p><strong>Adjusted p-value</strong>: 0.999</p></li>
<li><p><strong>Conclusion</strong>: No significant difference in weight loss between Diet 2 and Diet 1.</p></li>
</ul></li>
<li><p><strong>Comparison 3 vs.&nbsp;1</strong>:</p>
<ul>
<li><p><strong>Difference</strong>: 1.848</p></li>
<li><p><strong>Confidence Interval</strong>: [0.257, 3.440]</p></li>
<li><p><strong>Adjusted p-value</strong>: 0.019</p></li>
<li><p><strong>Conclusion</strong>: Diet 3 results in significantly greater weight loss compared to Diet 1.</p></li>
</ul></li>
<li><p><strong>Comparison 3 vs.&nbsp;2</strong>:</p>
<ul>
<li><p><strong>Difference</strong>: 1.880</p></li>
<li><p><strong>Confidence Interval</strong>: [0.306, 3.455]</p></li>
<li><p><strong>Adjusted p-value</strong>: 0.015</p></li>
<li><p><strong>Conclusion</strong>: Diet 3 also results in significantly greater weight loss compared to Diet 2.</p></li>
</ul></li>
</ol>
<p><strong>Key Takeaway</strong>:</p>
<ul>
<li>Diet 3 shows significantly higher weight loss than both Diet 1 and Diet 2, while Diets 1 and 2 do not differ significantly from each other.</li>
</ul>
<p>How much of the variation is explained? If you notice when you do a summary from a <code>lm()</code> (regression) model, it gives you the <span class="math inline">\(R^2\)</span> values directly (remember <span class="math inline">\(R^2 = \frac{SS_{model}}{SS_{Error}}\)</span>). Does <code>summary()</code> of your <code>aov</code> model give you that?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># How much variance?</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(<span class="at">formula =</span> weight_loss<span class="sc">$</span>loss <span class="sc">~</span> weight_loss<span class="sc">$</span>Diet, <span class="at">data =</span> weight_loss) <span class="ot">-&gt;</span> diet_lm</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(diet_lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = weight_loss$loss ~ weight_loss$Diet, data = weight_loss)

Residuals:
    Min      1Q  Median      3Q     Max 
-6.0088 -1.4769  0.1412  1.5018  6.0338 

Coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept)        2.0236     0.7389   2.739  0.00772 **
weight_loss$Diet   0.9426     0.3363   2.803  0.00645 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.399 on 74 degrees of freedom
Multiple R-squared:  0.096, Adjusted R-squared:  0.08378 
F-statistic: 7.858 on 1 and 74 DF,  p-value: 0.006455</code></pre>
</div>
</div>
<section id="summary" class="level3">
<h3 class="anchored" data-anchor-id="summary">Summary:</h3>
<ul>
<li><p><strong>Diet is a significant predictor</strong> of weight loss, with each diet level contributing approximately 0.943 kg additional weight loss.</p></li>
<li><p>The model explains a small but statistically significant portion of the variability in weight loss (R^2 %).</p></li>
<li><p>Residuals indicate variability not captured by the model, suggesting other factors may also play a role.</p></li>
</ul>
<p>Since I asked the question, the answer is probably no. Why does it not do this? Probably for historical reasons, which are a bit of a pain in the backside. That being said, there are some <code>tidy</code> ways to fix this issue. I’m going to use the <code>broom</code> package which allows us to clean up (or tidy if you will) the model objects. This will take the model object and pull out <em>all</em> the ANOVA table stuff and put it into a <code>tibble</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a> <span class="fu">library</span>( broom ) </span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="co"># use your model fit next (I called mine fit.diet)</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>tidy_diet <span class="ot">&lt;-</span> <span class="fu">tidy</span>( fit.diet )</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>tidy_diet</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 6
  term            df sumsq meansq statistic  p.value
  &lt;chr&gt;        &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 factor(Diet)     2  60.5  30.3       5.38  0.00660
2 Residuals       73 410.    5.62     NA    NA      </code></pre>
</div>
</div>
<p>Now, since it is all easily accessible, we can calculate the <span class="math inline">\(R^2\)</span> from the new model output.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimate the variance explained from the raw sums of squares</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a> r2_Diet <span class="ot">&lt;-</span> tidy_diet<span class="sc">$</span>sumsq[<span class="dv">1</span>] <span class="sc">/</span> <span class="fu">sum</span>( tidy_diet<span class="sc">$</span>sumsq )</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a> r2_Diet </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1285269</code></pre>
</div>
</div>
<section id="key-insights-1" class="level4">
<h4 class="anchored" data-anchor-id="key-insights-1">Key Insights:</h4>
<ol type="1">
<li><p><strong>Variance Explained</strong>:</p>
<ul>
<li>The <code>Diet</code> factor explains about <strong>12.85%</strong> of the total variation in weight loss among participants.</li>
</ul></li>
<li><p><strong>Significance</strong>:</p>
<ul>
<li>While statistically significant (from ANOVA results, p=0.0066), the R^2 value is relatively low, indicating that <code>Diet</code> alone is not a strong predictor of weight loss.</li>
</ul></li>
<li><p><strong>Unexplained Variance</strong>:</p>
<ul>
<li>The remaining <strong>87.15%</strong> of the variation in weight loss is attributed to other factors (e.g., individual differences, measurement error) or residual variance not explained by the model.</li>
</ul></li>
</ol>
<p><em>Gender:</em></p>
<p>The underlying linear model.</p>
<p><span class="math inline">\(y_{ij} = \mu + \tau_{gender, i} + \epsilon_j\)</span></p>
<p>Independent of the diet, test the null hypothesis <span class="math inline">\(H_O:\)</span> <em>There is no difference in weight loss between genders</em> (e.g., $*{gender-0} =* = 0.0 $). Is there evidence for one gender being significantly different than another? How much of the variation is explained (another <span class="math inline">\(R^2\)</span> by gender)?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>gender_wtLoss <span class="ot">&lt;-</span> weight_loss <span class="sc">%&gt;%</span> <span class="fu">select</span>(gender, Diet, loss) <span class="sc">%&gt;%</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">gender =</span> <span class="fu">as.factor</span>(gender))</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>fit.gender <span class="ot">&lt;-</span> <span class="fu">aov</span>(weight_loss<span class="sc">$</span>loss <span class="sc">~</span> weight_loss<span class="sc">$</span>gender, <span class="at">data =</span> weight_loss)</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit.gender)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   Df Sum Sq Mean Sq F value Pr(&gt;F)
weight_loss$gender  1    0.3   0.278   0.044  0.835
Residuals          74  470.7   6.360               </code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>tidy_gender <span class="ot">&lt;-</span> <span class="fu">tidy</span>(fit.gender)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(<span class="at">formula =</span> weight_loss<span class="sc">$</span>loss <span class="sc">~</span> weight_loss<span class="sc">$</span>gender, <span class="at">data =</span> weight_loss) <span class="ot">-&gt;</span> gender.lm</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(gender.lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = weight_loss$loss ~ weight_loss$gender, data = weight_loss)

Residuals:
    Min      1Q  Median      3Q     Max 
-5.9930 -1.6846 -0.2041  1.7264  5.1848 

Coefficients:
                   Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)          3.8930     0.3846  10.123  1.3e-15 ***
weight_loss$gender   0.1221     0.5836   0.209    0.835    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.522 on 74 degrees of freedom
Multiple R-squared:  0.0005914, Adjusted R-squared:  -0.01291 
F-statistic: 0.04379 on 1 and 74 DF,  p-value: 0.8348</code></pre>
</div>
</div>
</section>
</section>
<section id="gender-differences-in-weight-loss" class="level3">
<h3 class="anchored" data-anchor-id="gender-differences-in-weight-loss">Gender Differences in Weight Loss</h3>
<ol type="1">
<li><p><strong>Gender Effect</strong>:</p>
<ul>
<li>The difference in weight loss between genders is <strong>0.122 kg</strong>, with a p=0.835. This is not statistically significant.</li>
</ul></li>
<li><p><strong>Model Fit</strong>:</p>
<ul>
<li><p>R^2 = 0.00059: Gender explains <strong>0.059%</strong> of the variation in weight loss, which is negligible.</p></li>
<li><p>Residual standard error: <strong>2.522</strong>, indicating substantial unexplained variability.</p></li>
</ul></li>
<li><p><strong>Conclusion</strong>:</p>
<ul>
<li>There is no evidence that gender has a meaningful impact on weight loss. Other factors likely drive the observed variation.</li>
</ul></li>
</ol>
</section>
</section>
<section id="do-genders-respond-differently-to-diets" class="level1">
<h1>Do genders respond differently to diets?</h1>
<p><span class="math inline">\(y_{ijk} = \mu + \tau_{Diet,i} + \tau_{gender,j} + \epsilon_k\)</span></p>
<p>So here we do something a bit different. We want to simultaneously ask the following questions:</p>
<ul>
<li>Do diets influence weight loss?</li>
<li>Do genders influence weight loss?</li>
<li>Is there an interaction where different genders respond differently to different diets?</li>
</ul>
<p>In <span class="math inline">\(R\)</span>, this is done as:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># diet model</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>fit.diet</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
   aov(formula = loss ~ factor(Diet), data = weight_loss)

Terms:
                factor(Diet) Residuals
Sum of Squares       60.5270  410.4018
Deg. of Freedom            2        73

Residual standard error: 2.371064
Estimated effects may be unbalanced</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>tidy_diet</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 6
  term            df sumsq meansq statistic  p.value
  &lt;chr&gt;        &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 factor(Diet)     2  60.5  30.3       5.38  0.00660
2 Residuals       73 410.    5.62     NA    NA      </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># gender model</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>fit.gender</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
   aov(formula = weight_loss$loss ~ weight_loss$gender, data = weight_loss)

Terms:
                weight_loss$gender Residuals
Sum of Squares              0.2785  470.6503
Deg. of Freedom                  1        74

Residual standard error: 2.521932
Estimated effects may be unbalanced</code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>tidy_gender</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 6
  term                  df   sumsq meansq statistic p.value
  &lt;chr&gt;              &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;
1 weight_loss$gender     1   0.278  0.278    0.0438   0.835
2 Residuals             74 471.     6.36    NA       NA    </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># interaction model</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>weight_loss<span class="sc">$</span>interaction <span class="ot">&lt;-</span> <span class="fu">interaction</span>(weight_loss<span class="sc">$</span>gender, weight_loss<span class="sc">$</span>Diet)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>model_interaction <span class="ot">&lt;-</span> <span class="fu">lm</span>(loss <span class="sc">~</span> <span class="fu">interaction</span>(gender, Diet), <span class="at">data =</span> weight_loss)</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_interaction)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = loss ~ interaction(gender, Diet), data = weight_loss)

Residuals:
    Min      1Q  Median      3Q     Max 
-5.5091 -1.2958  0.0705  1.2159  5.4500 

Coefficients:
                             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                    3.0500     0.6197   4.922 5.49e-06 ***
interaction(gender, Diet)1.1   0.6000     0.9600   0.625   0.5340    
interaction(gender, Diet)0.2  -0.4429     0.8764  -0.505   0.6149    
interaction(gender, Diet)1.2   1.0591     0.9342   1.134   0.2608    
interaction(gender, Diet)0.3   2.8300     0.8616   3.284   0.0016 ** 
interaction(gender, Diet)1.3   1.1833     0.9122   1.297   0.1988    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.319 on 70 degrees of freedom
Multiple R-squared:  0.2009,    Adjusted R-squared:  0.1438 
F-statistic: 3.519 on 5 and 70 DF,  p-value: 0.006775</code></pre>
</div>
</div>
<section id="gender-and-diet-interaction-on-weight-loss" class="level3">
<h3 class="anchored" data-anchor-id="gender-and-diet-interaction-on-weight-loss">Gender and Diet Interaction on Weight Loss</h3>
<ol type="1">
<li><p><strong>Baseline Effect</strong>:</p>
<ul>
<li>The intercept (3.05) represents the mean weight loss for <code>gender = 0</code> and <code>Diet = 1</code>. It is significant (p&lt;0.001).</li>
</ul></li>
<li><p><strong>Significant Interaction</strong>:</p>
<ul>
<li><strong>Gender = 0, Diet = 3</strong> shows a significant additional effect (2.833, p=0.002), indicating that this group has a significantly different weight loss compared to the baseline.</li>
</ul></li>
<li><p><strong>Non-Significant Interactions</strong>:</p>
<ul>
<li>All other interaction terms are not significant (p&gt;0.05), suggesting no strong evidence of meaningful differences in weight loss for other gender-diet combinations.</li>
</ul></li>
<li><p><strong>Model Fit</strong>:</p>
<ul>
<li><p>R^2 = 0.20: The model explains <strong>20%</strong> of the variation in weight loss.</p></li>
<li><p><strong>Residual Standard Error</strong>: 2.319, reflecting moderate variability in residuals.</p></li>
</ul></li>
<li><p><strong>Conclusion</strong>:</p>
<ul>
<li>While the overall model is significant (F=3.519, p=0.0068), the interaction effects are weak except for <code>gender = 0, Diet = 3</code>. Diet appears to have a stronger influence on weight loss than gender.</li>
</ul></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># best model variance explained</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="which-model-is-best" class="level1">
<h1>Which Model is Best?</h1>
<p>The analysis revealed that diet significantly influences weight loss, with Diet 3 being the most effective for both genders. Gender alone does not have a meaningful impact on weight loss, explaining less than 0.1% of the variation, but there is a modest interaction effect between gender and diet. Specifically, males on Diet 3 experienced significantly greater weight loss compared to other groups. The interaction model, which considers both diet and gender, explains 20% of the variation in weight loss, making it the most informative. However, substantial unexplained variability indicates that other factors, such as age or activity levels, may also contribute to weight loss outcomes. Overall, diet remains the strongest predictor, and focusing on Diet 3 yields the best results across groups.</p>
<!-- -->

</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb37" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Analysis of Variance"</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a><span class="an">subtitle:</span><span class="co"> "In Class Activity"</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Ethan Pisterman"</span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a><span class="an">execute:</span><span class="co"> </span></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a><span class="co">  echo: true</span></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span><span class="co"> </span></span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: false</span></span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a><span class="an">abstract:</span><span class="co"> &gt; </span></span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a><span class="co"> This analysis examines the effects of diet and gender on weight loss using ANOVA models. Diet significantly impacts weight loss, with Diet 3 producing the greatest results. Gender alone has no meaningful effect, but males on Diet 3 show significantly higher weight loss. The interaction model explains 20% of the variation, confirming diet as the strongest predictor of weight loss.</span></span>
<span id="cb37-13"><a href="#cb37-13" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb37-14"><a href="#cb37-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-15"><a href="#cb37-15" aria-hidden="true" tabindex="-1"></a><span class="fu">### Introduction</span></span>
<span id="cb37-16"><a href="#cb37-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-17"><a href="#cb37-17" aria-hidden="true" tabindex="-1"></a>This analysis investigates the effects of diet and gender on weight loss over six weeks using data from 76 participants. The dataset includes demographic information (age, height, and gender), initial and post-diet weights, and one of three diet plans. Through exploratory data analysis and statistical modeling, we aim to determine whether diet significantly affects weight loss, whether gender plays a role, and if there is an interaction between diet and gender that impacts results. Using one-way and two-way ANOVA models, along with post-hoc tests, this study identifies key patterns and explains how much of the variability in weight loss is attributable to these factors. There are 76 observations of individuals with the following characteristics:</span>
<span id="cb37-18"><a href="#cb37-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-19"><a href="#cb37-19" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Gender (0/1)</span>
<span id="cb37-20"><a href="#cb37-20" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Age (earth years. 🤓)</span>
<span id="cb37-21"><a href="#cb37-21" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Height (cm)</span>
<span id="cb37-22"><a href="#cb37-22" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Pre.weight &amp; weight6weeks (kg)</span>
<span id="cb37-23"><a href="#cb37-23" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Diet (1,2,3)</span>
<span id="cb37-24"><a href="#cb37-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-25"><a href="#cb37-25" aria-hidden="true" tabindex="-1"></a>The data are located as a CSV file named <span class="in">`DietData.csv`</span> linked from the Canvas page. Load the data in and format things so they look correctly to you.</span>
<span id="cb37-26"><a href="#cb37-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-27"><a href="#cb37-27" aria-hidden="true" tabindex="-1"></a><span class="in">```{r setup, warning = FALSE, message = FALSE}</span></span>
<span id="cb37-28"><a href="#cb37-28" aria-hidden="true" tabindex="-1"></a><span class="in"># load the data here</span></span>
<span id="cb37-29"><a href="#cb37-29" aria-hidden="true" tabindex="-1"></a><span class="in">data &lt;- read.csv("~/Desktop/ENVS  543/ENVS543/dietdata.csv")</span></span>
<span id="cb37-30"><a href="#cb37-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-31"><a href="#cb37-31" aria-hidden="true" tabindex="-1"></a><span class="in">library(ggplot2)</span></span>
<span id="cb37-32"><a href="#cb37-32" aria-hidden="true" tabindex="-1"></a><span class="in">library(GGally)</span></span>
<span id="cb37-33"><a href="#cb37-33" aria-hidden="true" tabindex="-1"></a><span class="in">library(tidyverse)</span></span>
<span id="cb37-34"><a href="#cb37-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-35"><a href="#cb37-35" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb37-36"><a href="#cb37-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-37"><a href="#cb37-37" aria-hidden="true" tabindex="-1"></a><span class="fu">## Exploratory Data Analysis</span></span>
<span id="cb37-38"><a href="#cb37-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-39"><a href="#cb37-39" aria-hidden="true" tabindex="-1"></a>One of the first things to do is to look at the data and see if there are any obvious things. Go ahead and explore these data visually. What do you see?</span>
<span id="cb37-40"><a href="#cb37-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-43"><a href="#cb37-43" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb37-44"><a href="#cb37-44" aria-hidden="true" tabindex="-1"></a><span class="co"># Data visualization</span></span>
<span id="cb37-45"><a href="#cb37-45" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(data)</span>
<span id="cb37-46"><a href="#cb37-46" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data)</span>
<span id="cb37-47"><a href="#cb37-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-48"><a href="#cb37-48" aria-hidden="true" tabindex="-1"></a><span class="co"># Check for missing values</span></span>
<span id="cb37-49"><a href="#cb37-49" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(data))</span>
<span id="cb37-50"><a href="#cb37-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-51"><a href="#cb37-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-52"><a href="#cb37-52" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span></span>
<span id="cb37-53"><a href="#cb37-53" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(gender, Age, Height, pre.weight, weight6weeks, Diet) <span class="ot">-&gt;</span> pair_comp</span>
<span id="cb37-54"><a href="#cb37-54" aria-hidden="true" tabindex="-1"></a><span class="fu">ggpairs</span>(pair_comp)</span>
<span id="cb37-55"><a href="#cb37-55" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb37-56"><a href="#cb37-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-57"><a href="#cb37-57" aria-hidden="true" tabindex="-1"></a><span class="fu">### Key Insights from Output:</span></span>
<span id="cb37-58"><a href="#cb37-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-59"><a href="#cb37-59" aria-hidden="true" tabindex="-1"></a><span class="ss">1.  </span>**Age**: The participants' ages range from 16 to 60, with a median age of 39, representing a middle-aged group overall.</span>
<span id="cb37-60"><a href="#cb37-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-61"><a href="#cb37-61" aria-hidden="true" tabindex="-1"></a><span class="ss">2.  </span>**Height**: Heights range from 141 cm to 201 cm, with an average height of about 171 cm, showing a wide variation in stature.</span>
<span id="cb37-62"><a href="#cb37-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-63"><a href="#cb37-63" aria-hidden="true" tabindex="-1"></a><span class="ss">3.  </span>**Pre.weight and Weight Change**:</span>
<span id="cb37-64"><a href="#cb37-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-65"><a href="#cb37-65" aria-hidden="true" tabindex="-1"></a><span class="ss">    -   </span>Pre-experiment weights range from 58 kg to 88 kg, with a mean of 72.3 kg.</span>
<span id="cb37-66"><a href="#cb37-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-67"><a href="#cb37-67" aria-hidden="true" tabindex="-1"></a><span class="ss">    -   </span>Post-experiment weights (6 weeks later) are slightly lower on average (mean = 68.3 kg), suggesting a potential weight loss trend.</span>
<span id="cb37-68"><a href="#cb37-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-69"><a href="#cb37-69" aria-hidden="true" tabindex="-1"></a><span class="ss">4.  </span>**Diet Groups**: Participants are evenly distributed across the three diet types (mean \~ 2.0), allowing for fair comparisons between groups.</span>
<span id="cb37-70"><a href="#cb37-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-71"><a href="#cb37-71" aria-hidden="true" tabindex="-1"></a><span class="ss">5.  </span>**Gender**: Around 43% of participants are coded as <span class="in">`1`</span>, suggesting a near-balanced gender distribution.</span>
<span id="cb37-72"><a href="#cb37-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-73"><a href="#cb37-73" aria-hidden="true" tabindex="-1"></a><span class="fu">## Estimating Mean Values</span></span>
<span id="cb37-74"><a href="#cb37-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-75"><a href="#cb37-75" aria-hidden="true" tabindex="-1"></a>Make a table of Weight Loss by gender and diet.</span>
<span id="cb37-76"><a href="#cb37-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-77"><a href="#cb37-77" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, message = FALSE}</span></span>
<span id="cb37-78"><a href="#cb37-78" aria-hidden="true" tabindex="-1"></a><span class="in"># Table output</span></span>
<span id="cb37-79"><a href="#cb37-79" aria-hidden="true" tabindex="-1"></a><span class="in">data %&gt;% </span></span>
<span id="cb37-80"><a href="#cb37-80" aria-hidden="true" tabindex="-1"></a><span class="in">  select(gender, Age, pre.weight, Diet, weight6weeks) -&gt; weight_loss</span></span>
<span id="cb37-81"><a href="#cb37-81" aria-hidden="true" tabindex="-1"></a><span class="in">weight_loss %&gt;%</span></span>
<span id="cb37-82"><a href="#cb37-82" aria-hidden="true" tabindex="-1"></a><span class="in">  mutate(loss = pre.weight - weight6weeks) -&gt; weight_loss</span></span>
<span id="cb37-83"><a href="#cb37-83" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-84"><a href="#cb37-84" aria-hidden="true" tabindex="-1"></a><span class="in">summary_table &lt;- weight_loss %&gt;%</span></span>
<span id="cb37-85"><a href="#cb37-85" aria-hidden="true" tabindex="-1"></a><span class="in">  group_by(gender, Diet) %&gt;%</span></span>
<span id="cb37-86"><a href="#cb37-86" aria-hidden="true" tabindex="-1"></a><span class="in">  summarize(mean_loss = mean(loss, na.rm = TRUE)) %&gt;%</span></span>
<span id="cb37-87"><a href="#cb37-87" aria-hidden="true" tabindex="-1"></a><span class="in">  ungroup()</span></span>
<span id="cb37-88"><a href="#cb37-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-89"><a href="#cb37-89" aria-hidden="true" tabindex="-1"></a><span class="in">knitr::kable(summary_table, caption = "Mean Weight Loss by Gender and Diet")</span></span>
<span id="cb37-90"><a href="#cb37-90" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb37-91"><a href="#cb37-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-92"><a href="#cb37-92" aria-hidden="true" tabindex="-1"></a><span class="fu">### Key Insights:</span></span>
<span id="cb37-93"><a href="#cb37-93" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-94"><a href="#cb37-94" aria-hidden="true" tabindex="-1"></a><span class="ss">1.  </span>**Gender Differences**:</span>
<span id="cb37-95"><a href="#cb37-95" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-96"><a href="#cb37-96" aria-hidden="true" tabindex="-1"></a><span class="ss">    -   </span>Gender <span class="in">`0`</span> (e.g., Male) and Gender <span class="in">`1`</span> (e.g., Female) show varying weight loss trends across diets, with females generally losing more weight on average in most diets.</span>
<span id="cb37-97"><a href="#cb37-97" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-98"><a href="#cb37-98" aria-hidden="true" tabindex="-1"></a><span class="ss">        -   </span>Example: Diet 2 (Male: 2.61 kg vs. Female: 4.11 kg).</span>
<span id="cb37-99"><a href="#cb37-99" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-100"><a href="#cb37-100" aria-hidden="true" tabindex="-1"></a><span class="ss">2.  </span>**Most Effective Diets**:</span>
<span id="cb37-101"><a href="#cb37-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-102"><a href="#cb37-102" aria-hidden="true" tabindex="-1"></a><span class="ss">    -   </span>**Gender `0`**: Diet 3 has the highest mean weight loss (5.88 kg).</span>
<span id="cb37-103"><a href="#cb37-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-104"><a href="#cb37-104" aria-hidden="true" tabindex="-1"></a><span class="ss">    -   </span>**Gender `1`**: Diet 3 also shows strong results (4.23 kg), but Diet 2 is close (4.11 kg).</span>
<span id="cb37-105"><a href="#cb37-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-106"><a href="#cb37-106" aria-hidden="true" tabindex="-1"></a><span class="ss">3.  </span>**Least Effective Diets**:</span>
<span id="cb37-107"><a href="#cb37-107" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-108"><a href="#cb37-108" aria-hidden="true" tabindex="-1"></a><span class="ss">    -   </span>**Gender `0`**: Diet 2 results in the lowest mean weight loss (2.61 kg).</span>
<span id="cb37-109"><a href="#cb37-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-110"><a href="#cb37-110" aria-hidden="true" tabindex="-1"></a><span class="ss">    -   </span>**Gender `1`**: Diet 1 has the lowest mean weight loss (3.65 kg).</span>
<span id="cb37-111"><a href="#cb37-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-112"><a href="#cb37-112" aria-hidden="true" tabindex="-1"></a><span class="fu">## 1-Way Analysis of Variance</span></span>
<span id="cb37-113"><a href="#cb37-113" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-114"><a href="#cb37-114" aria-hidden="true" tabindex="-1"></a>*Diet Issues:*</span>
<span id="cb37-115"><a href="#cb37-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-116"><a href="#cb37-116" aria-hidden="true" tabindex="-1"></a>The underlying linear model.</span>
<span id="cb37-117"><a href="#cb37-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-118"><a href="#cb37-118" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb37-119"><a href="#cb37-119" aria-hidden="true" tabindex="-1"></a>y_{ij} = \mu + \tau_{Diet, i} + \epsilon_j</span>
<span id="cb37-120"><a href="#cb37-120" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb37-121"><a href="#cb37-121" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-122"><a href="#cb37-122" aria-hidden="true" tabindex="-1"></a>Test the null hypothesis, $H_O:$ *There is no effect of diet on weight loss* (e.g., $\tau_{Diet-1} = \tau_{Diet-2} = \tau_{Diet-3} = 0.0$). Is there evidence for one diet producing more weight loss than the others? Create an <span class="in">`aov`</span> analysis and assign it to the variable <span class="in">`fit.diet`</span> and examine its contents.</span>
<span id="cb37-123"><a href="#cb37-123" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-126"><a href="#cb37-126" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb37-127"><a href="#cb37-127" aria-hidden="true" tabindex="-1"></a><span class="co"># Define model</span></span>
<span id="cb37-128"><a href="#cb37-128" aria-hidden="true" tabindex="-1"></a>fit.diet <span class="ot">&lt;-</span> <span class="fu">aov</span>(loss <span class="sc">~</span> <span class="fu">factor</span>(Diet), <span class="at">data =</span> weight_loss)</span>
<span id="cb37-129"><a href="#cb37-129" aria-hidden="true" tabindex="-1"></a>fit.diet</span>
<span id="cb37-130"><a href="#cb37-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-131"><a href="#cb37-131" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(fit.diet)</span>
<span id="cb37-132"><a href="#cb37-132" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb37-133"><a href="#cb37-133" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-134"><a href="#cb37-134" aria-hidden="true" tabindex="-1"></a>**ANOVA Results:**</span>
<span id="cb37-135"><a href="#cb37-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-136"><a href="#cb37-136" aria-hidden="true" tabindex="-1"></a><span class="ss">1.  </span>**Evidence Against the Null Hypothesis**:</span>
<span id="cb37-137"><a href="#cb37-137" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-138"><a href="#cb37-138" aria-hidden="true" tabindex="-1"></a><span class="ss">    -   </span>The p-value for the <span class="in">`factor(Diet)`</span> term is **0.0066**, which is smaller than the significance threshold of 0.05.</span>
<span id="cb37-139"><a href="#cb37-139" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-140"><a href="#cb37-140" aria-hidden="true" tabindex="-1"></a><span class="ss">    -   </span>This provides strong evidence to reject H0H_0H0​. Hence, there is a statistically significant difference in weight loss among the diet groups.</span>
<span id="cb37-141"><a href="#cb37-141" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-142"><a href="#cb37-142" aria-hidden="true" tabindex="-1"></a><span class="ss">2.  </span>**Variance Partitioning**:</span>
<span id="cb37-143"><a href="#cb37-143" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-144"><a href="#cb37-144" aria-hidden="true" tabindex="-1"></a><span class="ss">    -   </span>The Sum of Squares for <span class="in">`factor(Diet)`</span> is **60.53**, while the residual variance is larger (**410.40**). This indicates that while diet contributes to differences in weight loss, individual variability or other factors explain a larger portion of the variation.</span>
<span id="cb37-145"><a href="#cb37-145" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-146"><a href="#cb37-146" aria-hidden="true" tabindex="-1"></a><span class="ss">3.  </span>**F-Statistic**:</span>
<span id="cb37-147"><a href="#cb37-147" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-148"><a href="#cb37-148" aria-hidden="true" tabindex="-1"></a><span class="ss">    -   </span>The F-value of **5.38** quantifies the ratio of diet-related variance to unexplained variance. The high value further supports the significance of diet as a factor.</span>
<span id="cb37-149"><a href="#cb37-149" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-150"><a href="#cb37-150" aria-hidden="true" tabindex="-1"></a><span class="ss">4.  </span>**Residual Standard Error**:</span>
<span id="cb37-151"><a href="#cb37-151" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-152"><a href="#cb37-152" aria-hidden="true" tabindex="-1"></a><span class="ss">    -   </span>The residual standard error of **2.37** indicates the average deviation of observed weight loss values from the model predictions.</span>
<span id="cb37-153"><a href="#cb37-153" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-154"><a href="#cb37-154" aria-hidden="true" tabindex="-1"></a>Are they all significantly different? Try the <span class="in">`TukeyHSD()`</span> Interpret the results.</span>
<span id="cb37-155"><a href="#cb37-155" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-158"><a href="#cb37-158" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb37-159"><a href="#cb37-159" aria-hidden="true" tabindex="-1"></a><span class="co"># Posthoc test</span></span>
<span id="cb37-160"><a href="#cb37-160" aria-hidden="true" tabindex="-1"></a>tuk <span class="ot">&lt;-</span> <span class="fu">TukeyHSD</span>(fit.diet)</span>
<span id="cb37-161"><a href="#cb37-161" aria-hidden="true" tabindex="-1"></a>tuk</span>
<span id="cb37-162"><a href="#cb37-162" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb37-163"><a href="#cb37-163" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-164"><a href="#cb37-164" aria-hidden="true" tabindex="-1"></a>**Post-hoc Summary:**</span>
<span id="cb37-165"><a href="#cb37-165" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-166"><a href="#cb37-166" aria-hidden="true" tabindex="-1"></a><span class="ss">1.  </span>**Comparison 2 vs. 1**:</span>
<span id="cb37-167"><a href="#cb37-167" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-168"><a href="#cb37-168" aria-hidden="true" tabindex="-1"></a><span class="ss">    -   </span>**Difference**: -0.032</span>
<span id="cb37-169"><a href="#cb37-169" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-170"><a href="#cb37-170" aria-hidden="true" tabindex="-1"></a><span class="ss">    -   </span>**Confidence Interval**: <span class="sc">\[</span>-1.653, 1.589<span class="sc">\]</span></span>
<span id="cb37-171"><a href="#cb37-171" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-172"><a href="#cb37-172" aria-hidden="true" tabindex="-1"></a><span class="ss">    -   </span>**Adjusted p-value**: 0.999</span>
<span id="cb37-173"><a href="#cb37-173" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-174"><a href="#cb37-174" aria-hidden="true" tabindex="-1"></a><span class="ss">    -   </span>**Conclusion**: No significant difference in weight loss between Diet 2 and Diet 1.</span>
<span id="cb37-175"><a href="#cb37-175" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-176"><a href="#cb37-176" aria-hidden="true" tabindex="-1"></a><span class="ss">2.  </span>**Comparison 3 vs. 1**:</span>
<span id="cb37-177"><a href="#cb37-177" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-178"><a href="#cb37-178" aria-hidden="true" tabindex="-1"></a><span class="ss">    -   </span>**Difference**: 1.848</span>
<span id="cb37-179"><a href="#cb37-179" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-180"><a href="#cb37-180" aria-hidden="true" tabindex="-1"></a><span class="ss">    -   </span>**Confidence Interval**: <span class="sc">\[</span>0.257, 3.440<span class="sc">\]</span></span>
<span id="cb37-181"><a href="#cb37-181" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-182"><a href="#cb37-182" aria-hidden="true" tabindex="-1"></a><span class="ss">    -   </span>**Adjusted p-value**: 0.019</span>
<span id="cb37-183"><a href="#cb37-183" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-184"><a href="#cb37-184" aria-hidden="true" tabindex="-1"></a><span class="ss">    -   </span>**Conclusion**: Diet 3 results in significantly greater weight loss compared to Diet 1.</span>
<span id="cb37-185"><a href="#cb37-185" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-186"><a href="#cb37-186" aria-hidden="true" tabindex="-1"></a><span class="ss">3.  </span>**Comparison 3 vs. 2**:</span>
<span id="cb37-187"><a href="#cb37-187" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-188"><a href="#cb37-188" aria-hidden="true" tabindex="-1"></a><span class="ss">    -   </span>**Difference**: 1.880</span>
<span id="cb37-189"><a href="#cb37-189" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-190"><a href="#cb37-190" aria-hidden="true" tabindex="-1"></a><span class="ss">    -   </span>**Confidence Interval**: <span class="sc">\[</span>0.306, 3.455<span class="sc">\]</span></span>
<span id="cb37-191"><a href="#cb37-191" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-192"><a href="#cb37-192" aria-hidden="true" tabindex="-1"></a><span class="ss">    -   </span>**Adjusted p-value**: 0.015</span>
<span id="cb37-193"><a href="#cb37-193" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-194"><a href="#cb37-194" aria-hidden="true" tabindex="-1"></a><span class="ss">    -   </span>**Conclusion**: Diet 3 also results in significantly greater weight loss compared to Diet 2.</span>
<span id="cb37-195"><a href="#cb37-195" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-196"><a href="#cb37-196" aria-hidden="true" tabindex="-1"></a>**Key Takeaway**:</span>
<span id="cb37-197"><a href="#cb37-197" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-198"><a href="#cb37-198" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Diet 3 shows significantly higher weight loss than both Diet 1 and Diet 2, while Diets 1 and 2 do not differ significantly from each other.</span>
<span id="cb37-199"><a href="#cb37-199" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-200"><a href="#cb37-200" aria-hidden="true" tabindex="-1"></a>How much of the variation is explained? If you notice when you do a summary from a <span class="in">`lm()`</span> (regression) model, it gives you the $R^2$ values directly (remember $R^2 = \frac{SS_{model}}{SS_{Error}}$). Does <span class="in">`summary()`</span> of your <span class="in">`aov`</span> model give you that?</span>
<span id="cb37-201"><a href="#cb37-201" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-204"><a href="#cb37-204" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb37-205"><a href="#cb37-205" aria-hidden="true" tabindex="-1"></a><span class="co"># How much variance?</span></span>
<span id="cb37-206"><a href="#cb37-206" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(<span class="at">formula =</span> weight_loss<span class="sc">$</span>loss <span class="sc">~</span> weight_loss<span class="sc">$</span>Diet, <span class="at">data =</span> weight_loss) <span class="ot">-&gt;</span> diet_lm</span>
<span id="cb37-207"><a href="#cb37-207" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(diet_lm)</span>
<span id="cb37-208"><a href="#cb37-208" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb37-209"><a href="#cb37-209" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-210"><a href="#cb37-210" aria-hidden="true" tabindex="-1"></a><span class="fu">### Summary:</span></span>
<span id="cb37-211"><a href="#cb37-211" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-212"><a href="#cb37-212" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**Diet is a significant predictor** of weight loss, with each diet level contributing approximately 0.943 kg additional weight loss.</span>
<span id="cb37-213"><a href="#cb37-213" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-214"><a href="#cb37-214" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>The model explains a small but statistically significant portion of the variability in weight loss (R\^2 \approx 9.6%).</span>
<span id="cb37-215"><a href="#cb37-215" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-216"><a href="#cb37-216" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Residuals indicate variability not captured by the model, suggesting other factors may also play a role.</span>
<span id="cb37-217"><a href="#cb37-217" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-218"><a href="#cb37-218" aria-hidden="true" tabindex="-1"></a>Since I asked the question, the answer is probably no. Why does it not do this? Probably for historical reasons, which are a bit of a pain in the backside. That being said, there are some <span class="in">`tidy`</span> ways to fix this issue. I'm going to use the <span class="in">`broom`</span> package which allows us to clean up (or tidy if you will) the model objects. This will take the model object and pull out *all* the ANOVA table stuff and put it into a <span class="in">`tibble`</span>.</span>
<span id="cb37-219"><a href="#cb37-219" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-222"><a href="#cb37-222" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb37-223"><a href="#cb37-223" aria-hidden="true" tabindex="-1"></a> <span class="fu">library</span>( broom ) </span>
<span id="cb37-224"><a href="#cb37-224" aria-hidden="true" tabindex="-1"></a><span class="co"># use your model fit next (I called mine fit.diet)</span></span>
<span id="cb37-225"><a href="#cb37-225" aria-hidden="true" tabindex="-1"></a>tidy_diet <span class="ot">&lt;-</span> <span class="fu">tidy</span>( fit.diet )</span>
<span id="cb37-226"><a href="#cb37-226" aria-hidden="true" tabindex="-1"></a>tidy_diet</span>
<span id="cb37-227"><a href="#cb37-227" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb37-228"><a href="#cb37-228" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-229"><a href="#cb37-229" aria-hidden="true" tabindex="-1"></a>Now, since it is all easily accessible, we can calculate the $R^2$ from the new model output.</span>
<span id="cb37-230"><a href="#cb37-230" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-233"><a href="#cb37-233" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb37-234"><a href="#cb37-234" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimate the variance explained from the raw sums of squares</span></span>
<span id="cb37-235"><a href="#cb37-235" aria-hidden="true" tabindex="-1"></a> r2_Diet <span class="ot">&lt;-</span> tidy_diet<span class="sc">$</span>sumsq[<span class="dv">1</span>] <span class="sc">/</span> <span class="fu">sum</span>( tidy_diet<span class="sc">$</span>sumsq )</span>
<span id="cb37-236"><a href="#cb37-236" aria-hidden="true" tabindex="-1"></a> r2_Diet </span>
<span id="cb37-237"><a href="#cb37-237" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb37-238"><a href="#cb37-238" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-239"><a href="#cb37-239" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Key Insights:</span></span>
<span id="cb37-240"><a href="#cb37-240" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-241"><a href="#cb37-241" aria-hidden="true" tabindex="-1"></a><span class="ss">1.  </span>**Variance Explained**:</span>
<span id="cb37-242"><a href="#cb37-242" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-243"><a href="#cb37-243" aria-hidden="true" tabindex="-1"></a><span class="ss">    -   </span>The <span class="in">`Diet`</span> factor explains about **12.85%** of the total variation in weight loss among participants.</span>
<span id="cb37-244"><a href="#cb37-244" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-245"><a href="#cb37-245" aria-hidden="true" tabindex="-1"></a><span class="ss">2.  </span>**Significance**:</span>
<span id="cb37-246"><a href="#cb37-246" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-247"><a href="#cb37-247" aria-hidden="true" tabindex="-1"></a><span class="ss">    -   </span>While statistically significant (from ANOVA results, p=0.0066), the R\^2 value is relatively low, indicating that <span class="in">`Diet`</span> alone is not a strong predictor of weight loss.</span>
<span id="cb37-248"><a href="#cb37-248" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-249"><a href="#cb37-249" aria-hidden="true" tabindex="-1"></a><span class="ss">3.  </span>**Unexplained Variance**:</span>
<span id="cb37-250"><a href="#cb37-250" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-251"><a href="#cb37-251" aria-hidden="true" tabindex="-1"></a><span class="ss">    -   </span>The remaining **87.15%** of the variation in weight loss is attributed to other factors (e.g., individual differences, measurement error) or residual variance not explained by the model.</span>
<span id="cb37-252"><a href="#cb37-252" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-253"><a href="#cb37-253" aria-hidden="true" tabindex="-1"></a>*Gender:*</span>
<span id="cb37-254"><a href="#cb37-254" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-255"><a href="#cb37-255" aria-hidden="true" tabindex="-1"></a>The underlying linear model.</span>
<span id="cb37-256"><a href="#cb37-256" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-257"><a href="#cb37-257" aria-hidden="true" tabindex="-1"></a>$y_{ij} = \mu + \tau_{gender, i} + \epsilon_j$</span>
<span id="cb37-258"><a href="#cb37-258" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-259"><a href="#cb37-259" aria-hidden="true" tabindex="-1"></a>Independent of the diet, test the null hypothesis $H_O:$ *There is no difference in weight loss between genders* (e.g., \$\tau<span class="sc">\*</span>{gender-0} =<span class="sc">\*</span> \tau{gender-2} = 0.0 \$). Is there evidence for one gender being significantly different than another? How much of the variation is explained (another $R^2$ by gender)?</span>
<span id="cb37-260"><a href="#cb37-260" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-263"><a href="#cb37-263" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb37-264"><a href="#cb37-264" aria-hidden="true" tabindex="-1"></a>gender_wtLoss <span class="ot">&lt;-</span> weight_loss <span class="sc">%&gt;%</span> <span class="fu">select</span>(gender, Diet, loss) <span class="sc">%&gt;%</span></span>
<span id="cb37-265"><a href="#cb37-265" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">gender =</span> <span class="fu">as.factor</span>(gender))</span>
<span id="cb37-266"><a href="#cb37-266" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-267"><a href="#cb37-267" aria-hidden="true" tabindex="-1"></a>fit.gender <span class="ot">&lt;-</span> <span class="fu">aov</span>(weight_loss<span class="sc">$</span>loss <span class="sc">~</span> weight_loss<span class="sc">$</span>gender, <span class="at">data =</span> weight_loss)</span>
<span id="cb37-268"><a href="#cb37-268" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit.gender)</span>
<span id="cb37-269"><a href="#cb37-269" aria-hidden="true" tabindex="-1"></a>tidy_gender <span class="ot">&lt;-</span> <span class="fu">tidy</span>(fit.gender)</span>
<span id="cb37-270"><a href="#cb37-270" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-271"><a href="#cb37-271" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(<span class="at">formula =</span> weight_loss<span class="sc">$</span>loss <span class="sc">~</span> weight_loss<span class="sc">$</span>gender, <span class="at">data =</span> weight_loss) <span class="ot">-&gt;</span> gender.lm</span>
<span id="cb37-272"><a href="#cb37-272" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(gender.lm)</span>
<span id="cb37-273"><a href="#cb37-273" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb37-274"><a href="#cb37-274" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-275"><a href="#cb37-275" aria-hidden="true" tabindex="-1"></a><span class="fu">### Gender Differences in Weight Loss</span></span>
<span id="cb37-276"><a href="#cb37-276" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-277"><a href="#cb37-277" aria-hidden="true" tabindex="-1"></a><span class="ss">1.  </span>**Gender Effect**:</span>
<span id="cb37-278"><a href="#cb37-278" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-279"><a href="#cb37-279" aria-hidden="true" tabindex="-1"></a><span class="ss">    -   </span>The difference in weight loss between genders is **0.122 kg**, with a p=0.835. This is not statistically significant.</span>
<span id="cb37-280"><a href="#cb37-280" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-281"><a href="#cb37-281" aria-hidden="true" tabindex="-1"></a><span class="ss">2.  </span>**Model Fit**:</span>
<span id="cb37-282"><a href="#cb37-282" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-283"><a href="#cb37-283" aria-hidden="true" tabindex="-1"></a><span class="ss">    -   </span>R\^2 = 0.00059: Gender explains **0.059%** of the variation in weight loss, which is negligible.</span>
<span id="cb37-284"><a href="#cb37-284" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-285"><a href="#cb37-285" aria-hidden="true" tabindex="-1"></a><span class="ss">    -   </span>Residual standard error: **2.522**, indicating substantial unexplained variability.</span>
<span id="cb37-286"><a href="#cb37-286" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-287"><a href="#cb37-287" aria-hidden="true" tabindex="-1"></a><span class="ss">3.  </span>**Conclusion**:</span>
<span id="cb37-288"><a href="#cb37-288" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-289"><a href="#cb37-289" aria-hidden="true" tabindex="-1"></a><span class="ss">    -   </span>There is no evidence that gender has a meaningful impact on weight loss. Other factors likely drive the observed variation.</span>
<span id="cb37-290"><a href="#cb37-290" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-291"><a href="#cb37-291" aria-hidden="true" tabindex="-1"></a><span class="fu"># Do genders respond differently to diets?</span></span>
<span id="cb37-292"><a href="#cb37-292" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-293"><a href="#cb37-293" aria-hidden="true" tabindex="-1"></a>$y_{ijk} = \mu + \tau_{Diet,i} + \tau_{gender,j} + \epsilon_k$</span>
<span id="cb37-294"><a href="#cb37-294" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-295"><a href="#cb37-295" aria-hidden="true" tabindex="-1"></a>So here we do something a bit different. We want to simultaneously ask the following questions:</span>
<span id="cb37-296"><a href="#cb37-296" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-297"><a href="#cb37-297" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Do diets influence weight loss?</span>
<span id="cb37-298"><a href="#cb37-298" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Do genders influence weight loss?</span>
<span id="cb37-299"><a href="#cb37-299" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>Is there an interaction where different genders respond differently to different diets?</span>
<span id="cb37-300"><a href="#cb37-300" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-301"><a href="#cb37-301" aria-hidden="true" tabindex="-1"></a>In $R$, this is done as:</span>
<span id="cb37-302"><a href="#cb37-302" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-305"><a href="#cb37-305" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb37-306"><a href="#cb37-306" aria-hidden="true" tabindex="-1"></a><span class="co"># diet model</span></span>
<span id="cb37-307"><a href="#cb37-307" aria-hidden="true" tabindex="-1"></a>fit.diet</span>
<span id="cb37-308"><a href="#cb37-308" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-309"><a href="#cb37-309" aria-hidden="true" tabindex="-1"></a>tidy_diet</span>
<span id="cb37-310"><a href="#cb37-310" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb37-311"><a href="#cb37-311" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-314"><a href="#cb37-314" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb37-315"><a href="#cb37-315" aria-hidden="true" tabindex="-1"></a><span class="co"># gender model</span></span>
<span id="cb37-316"><a href="#cb37-316" aria-hidden="true" tabindex="-1"></a>fit.gender</span>
<span id="cb37-317"><a href="#cb37-317" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-318"><a href="#cb37-318" aria-hidden="true" tabindex="-1"></a>tidy_gender</span>
<span id="cb37-319"><a href="#cb37-319" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb37-320"><a href="#cb37-320" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-323"><a href="#cb37-323" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb37-324"><a href="#cb37-324" aria-hidden="true" tabindex="-1"></a><span class="co"># interaction model</span></span>
<span id="cb37-325"><a href="#cb37-325" aria-hidden="true" tabindex="-1"></a>weight_loss<span class="sc">$</span>interaction <span class="ot">&lt;-</span> <span class="fu">interaction</span>(weight_loss<span class="sc">$</span>gender, weight_loss<span class="sc">$</span>Diet)</span>
<span id="cb37-326"><a href="#cb37-326" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-327"><a href="#cb37-327" aria-hidden="true" tabindex="-1"></a>model_interaction <span class="ot">&lt;-</span> <span class="fu">lm</span>(loss <span class="sc">~</span> <span class="fu">interaction</span>(gender, Diet), <span class="at">data =</span> weight_loss)</span>
<span id="cb37-328"><a href="#cb37-328" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-329"><a href="#cb37-329" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-330"><a href="#cb37-330" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_interaction)</span>
<span id="cb37-331"><a href="#cb37-331" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-332"><a href="#cb37-332" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb37-333"><a href="#cb37-333" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-334"><a href="#cb37-334" aria-hidden="true" tabindex="-1"></a><span class="fu">### Gender and Diet Interaction on Weight Loss</span></span>
<span id="cb37-335"><a href="#cb37-335" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-336"><a href="#cb37-336" aria-hidden="true" tabindex="-1"></a><span class="ss">1.  </span>**Baseline Effect**:</span>
<span id="cb37-337"><a href="#cb37-337" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-338"><a href="#cb37-338" aria-hidden="true" tabindex="-1"></a><span class="ss">    -   </span>The intercept (3.05) represents the mean weight loss for <span class="in">`gender = 0`</span> and <span class="in">`Diet = 1`</span>. It is significant (p<span class="sc">\&lt;</span>0.001).</span>
<span id="cb37-339"><a href="#cb37-339" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-340"><a href="#cb37-340" aria-hidden="true" tabindex="-1"></a><span class="ss">2.  </span>**Significant Interaction**:</span>
<span id="cb37-341"><a href="#cb37-341" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-342"><a href="#cb37-342" aria-hidden="true" tabindex="-1"></a><span class="ss">    -   </span>**Gender = 0, Diet = 3** shows a significant additional effect (2.833, p=0.002), indicating that this group has a significantly different weight loss compared to the baseline.</span>
<span id="cb37-343"><a href="#cb37-343" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-344"><a href="#cb37-344" aria-hidden="true" tabindex="-1"></a><span class="ss">3.  </span>**Non-Significant Interactions**:</span>
<span id="cb37-345"><a href="#cb37-345" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-346"><a href="#cb37-346" aria-hidden="true" tabindex="-1"></a><span class="ss">    -   </span>All other interaction terms are not significant (p<span class="sc">\&gt;</span>0.05), suggesting no strong evidence of meaningful differences in weight loss for other gender-diet combinations.</span>
<span id="cb37-347"><a href="#cb37-347" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-348"><a href="#cb37-348" aria-hidden="true" tabindex="-1"></a><span class="ss">4.  </span>**Model Fit**:</span>
<span id="cb37-349"><a href="#cb37-349" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-350"><a href="#cb37-350" aria-hidden="true" tabindex="-1"></a><span class="ss">    -   </span>R\^2 = 0.20: The model explains **20%** of the variation in weight loss.</span>
<span id="cb37-351"><a href="#cb37-351" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-352"><a href="#cb37-352" aria-hidden="true" tabindex="-1"></a><span class="ss">    -   </span>**Residual Standard Error**: 2.319, reflecting moderate variability in residuals.</span>
<span id="cb37-353"><a href="#cb37-353" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-354"><a href="#cb37-354" aria-hidden="true" tabindex="-1"></a><span class="ss">5.  </span>**Conclusion**:</span>
<span id="cb37-355"><a href="#cb37-355" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-356"><a href="#cb37-356" aria-hidden="true" tabindex="-1"></a><span class="ss">    -   </span>While the overall model is significant (F=3.519, p=0.0068), the interaction effects are weak except for <span class="in">`gender = 0, Diet = 3`</span>. Diet appears to have a stronger influence on weight loss than gender.</span>
<span id="cb37-357"><a href="#cb37-357" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-360"><a href="#cb37-360" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb37-361"><a href="#cb37-361" aria-hidden="true" tabindex="-1"></a><span class="co"># best model variance explained</span></span>
<span id="cb37-362"><a href="#cb37-362" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb37-363"><a href="#cb37-363" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-364"><a href="#cb37-364" aria-hidden="true" tabindex="-1"></a><span class="fu"># Which Model is Best?</span></span>
<span id="cb37-365"><a href="#cb37-365" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-366"><a href="#cb37-366" aria-hidden="true" tabindex="-1"></a>The analysis revealed that diet significantly influences weight loss, with Diet 3 being the most effective for both genders. Gender alone does not have a meaningful impact on weight loss, explaining less than 0.1% of the variation, but there is a modest interaction effect between gender and diet. Specifically, males on Diet 3 experienced significantly greater weight loss compared to other groups. The interaction model, which considers both diet and gender, explains 20% of the variation in weight loss, making it the most informative. However, substantial unexplained variability indicates that other factors, such as age or activity levels, may also contribute to weight loss outcomes. Overall, diet remains the strongest predictor, and focusing on Diet 3 yields the best results across groups.</span>
</code><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->




</body></html>