---
title: ""
output: html_document
format:
    html:
      toc: true
    pdf:
      toc: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# *Curriculum Vitae*

### Ethan Pisterman

**Email:** [pistermanet\@vcu.edu](mailto:pistermanet@vcu.edu){.email}\
**Phone:** (757) 650-8276\
**GitHub:** [github.com/ethantp](https://github.com/ethantp)

------------------------------------------------------------------------

## Summary

Detail-oriented student studying Environmental Studies at Virginia Commonwealth University with extensive experience in data collection and analysis. Proficient in many analytic tools like R, Microsoft Office, and ArcGis that assist in managing ecological datum. Eager to carry analytical skills and hands-on experience to contribute to a career in data analytics for a government agency focused on ecological/geospacial analysis.

------------------------------------------------------------------------

## Technical Skills

-   **Programming Languages:** R and Markdown
-   **Tools & Technologies:** Quarto, Git, ESRI, etc.
-   **Software:** ArcGIS, ArcGIS Pro, Microsoft Excel, etc.
-   **Methodologies:** Data Analysis, Field Research, etc.

------------------------------------------------------------------------

## Education

**Bachelor of Science, Environmental Studies**\
*Virginia Commonwealth University*\
*Richmond, Virginia*\
*September 2021 -- May 2025*

-   Relevant coursework:
    -   ENVS 543: Environmental Data Literacy
    -   ENVS 343: Data Literacy
    -   ENVS 591: Intro to GIS
-   GPA: 3.0

------------------------------------------------------------------------

## Projects

### Virginia State Park Infographic Web App

-   **Description:** A Magnum Opus finalizing my gained experience in ArcGIS online and ArcGIS pro that provides state park information combined with statewide ecological survey data that determines the level of ecological importance in and around these state parks.
-   **Technologies Used:** ArcGis Online, ArcGIS Pro.
-   **Role:** Wrangled data online provided by both state agencies and citizen science sources.
-   View the web app [here](https://experience.arcgis.com/experience/abc27eea4625474f944324852a123415).

------------------------------------------------------------------------

## Work Experience

### Assisstant General Manager

**Papa John's Pizza**\
*Richmond, Virginia*\
*October 2022 -- Present*

-   Responsible for operational oversight, financial management, customer service management and engagement, and strategic planning in downtown Richmond's busiest location.

### Shift Supervisor

**Saladworks**\
*Virginia Beach, Virginia*\
*October 2019 -- October 2022*

-   Managed team of tightly knit students during the global pandemic, and gained skills important for restaurant upkeep, monthly maintenance upkeep, customer service, and upheld compliance and safety standards during the pandemic.

------------------------------------------------------------------------

## Professional Affiliations/Clubs

-   **VCU EDM Club** -- Member, April 2024 -- Present

------------------------------------------------------------------------

## Volunteer Experience

### Role Title

**Kellam High School Environmental Club**\
*Virginia Beach, Virginia*\
*April 2019 -- March 2020*

-   Was involved in multiple of beach cleanups held by my high school. Every month we would collect trash on the nearby beach, reducing the impact of trash in the local waterways and beaches, while also preserving the natural beauty of Sandbridge Beach.

------------------------------------------------------------------------
